// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDonDQnMfxxFWlOxSb7e28l60vzdIhdSpw',
    appId: '1:483316879705:web:af2c8f5f07e7665e52fc48',
    messagingSenderId: '483316879705',
    projectId: 'dsix-fcc69',
    authDomain: 'dsix-fcc69.firebaseapp.com',
    storageBucket: 'dsix-fcc69.appspot.com',
    measurementId: 'G-LPB7FLW5Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6bN4SwiTLEdxJ2S-57GDS9kBf-nbXA14',
    appId: '1:483316879705:android:eb3fa1f7789c85aa52fc48',
    messagingSenderId: '483316879705',
    projectId: 'dsix-fcc69',
    storageBucket: 'dsix-fcc69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf4JnJX93CibO_ivhnv7jYDDRiZhzUZiQ',
    appId: '1:483316879705:ios:46b7eab2de5931fb52fc48',
    messagingSenderId: '483316879705',
    projectId: 'dsix-fcc69',
    storageBucket: 'dsix-fcc69.appspot.com',
    iosClientId: '483316879705-0lenbotac54takpejjbt2edl6rscj6o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dsix',
  );
}
