import 'package:dsix/model/combat/armor.dart';
import 'package:dsix/model/combat/attack.dart';
import 'package:dsix/model/combat/damage.dart';
import 'package:dsix/model/combat/range.dart';
import 'dart:math';
import 'item.dart';

class Shop {
  List<Item> createRandomLoot(int xp) {
    int lootValue = 0;
    switch (xp) {
      case 4:
        lootValue = 50 + (Random().nextDouble() * 100).toInt();
        break;
      case 10:
        lootValue = 100 + (Random().nextDouble() * 150).toInt();
        break;
      case 14:
        lootValue = 150 + (Random().nextDouble() * 200).toInt();
        break;
    }

    List<Item> loot = [];
    int currentValue = 0;

    while (currentValue < lootValue) {
      int leftOverAmount = lootValue - currentValue;

      if (leftOverAmount < 100) {
        Item gold = Item(
            name: 'gold',
            description: 'shiny',
            itemSlot: '',
            type: 'gold',
            needsReload: false,
            isLoaded: false,
            effects: [],
            attacks: [],
            armor: Armor.empty(),
            numberOfUses: 0,
            weight: 0,
            value: leftOverAmount);

        loot.add(gold);
        currentValue += leftOverAmount;
      } else {
        Item newItem = randomItem();
        if (currentValue + newItem.value <= lootValue) {
          loot.add(newItem);
          currentValue += newItem.value;
        }
      }
    }

    return loot;
  }

  Item randomItem() {
    late Item newItem;
    late int randomItem;
    switch (randomItemCategory()) {
      case 'lightWeapons':
        randomItem = Random().nextInt(lightWeapons.length);
        newItem = lightWeapons[randomItem];
        break;

      case 'heavyWeapons':
        randomItem = Random().nextInt(heavyWeapons.length);
        newItem = heavyWeapons[randomItem];
        break;

      case 'rangedWeapons':
        randomItem = Random().nextInt(rangedWeapons.length);
        newItem = rangedWeapons[randomItem];
        break;

      case 'armor':
        randomItem = Random().nextInt(armor.length);
        newItem = armor[randomItem];
        break;
      case 'ancient':
        randomItem = Random().nextInt(ancient.length);
        newItem = ancient[randomItem];
        break;
      case 'consumable':
        randomItem = Random().nextInt(consumable.length);
        newItem = consumable[randomItem];
        break;
    }
    return newItem;
  }

  String randomItemCategory() {
    List<String> category = [
      'lightWeapons',
      'heavyWeapons',
      'rangedWeapons',
      'armor',
      // 'ancient',
      // 'consumable',
    ];
    int randomCategory = Random().nextInt(category.length);
    return category[randomCategory];
  }

  List<Item> lightWeapons = [
    Item(
      name: 'batton',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      isLoaded: false,
      needsReload: false,
      effects: [],
      attacks: [
        Attack(
          name: 'jab',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 0,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'dagger',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'slash',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 3.5,
            max: 8,
            width: 16,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'flail',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 12,
            max: 13,
            width: 22,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'gladius',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'slash',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 5,
            max: 10,
            width: 20,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'mace',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      isLoaded: false,
      needsReload: false,
      effects: [],
      attacks: [
        Attack(
          name: 'crush',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 0,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'morning star',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'crush',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 0,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'nunchaku',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'slash',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 3.5,
            max: 6,
            width: 18,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'poison dagger',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'slash',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 3.5,
            max: 8,
            width: 16,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'rapier',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'slash',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 5,
            max: 20,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'saber',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'slash',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 5,
            max: 10,
            width: 20,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'sharp fist',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'slash',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 3.5,
            max: 10,
            width: 10,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'short spear',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'thrust',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 25,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'short sword',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'slash',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 5,
            max: 10,
            width: 20,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'talon',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'thrust',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 3.5,
            max: 15,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'wood axe',
      description: '',
      itemSlot: 'one hand',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 10,
            max: 11,
            width: 20,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
  ];

  List<Item> heavyWeapons = [
    Item(
      name: 'giant club',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'slam',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 6,
            max: 28,
            width: 8,
            shape: 'cone',
          ),
          effects: [],
        ),
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 16,
            width: 25,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'war hammer',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 14.5,
            max: 15.5,
            width: 32,
            shape: 'cone',
          ),
          effects: [],
        ),
        Attack(
          name: 'slam',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 18,
            max: 0,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'katana',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 10,
            width: 30,
            shape: 'cone',
          ),
          effects: [],
        ),
        Attack(
          name: 'thrust',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 25,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'long sword',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 10,
            width: 30,
            shape: 'cone',
          ),
          effects: [],
        ),
        Attack(
          name: 'thrust',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 25,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'battle axe',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 9,
            max: 15,
            width: 22,
            shape: 'cone',
          ),
          effects: [],
        ),
        Attack(
          name: 'slam',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 13,
            max: 7,
            width: 4,
            shape: 'diamond',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'double sword',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 10,
            max: 11,
            width: 20,
            shape: 'cone',
          ),
          effects: [],
        ),
        Attack(
          name: 'thrust',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 22.5,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'quarterstaff',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 10,
            max: 11,
            width: 20,
            shape: 'cone',
          ),
          effects: [],
        ),
        Attack(
          name: 'slam',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 5,
            max: 18,
            width: 4,
            shape: 'rectangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'trident',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'thrust',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 15,
            max: 40,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'long spear',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'thrust',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 15,
            max: 40,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'great sword',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 10,
            max: 20,
            width: 30,
            shape: 'cone',
          ),
          effects: [],
        ),
        Attack(
          name: 'slam',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 8,
            max: 30,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'halberd',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'thrust',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 18,
            max: 38,
            width: 10,
            shape: 'triangle',
          ),
          effects: [],
        ),
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 20,
            max: 24,
            width: 40,
            shape: 'cone',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'long axe',
      description: '',
      itemSlot: 'two hands',
      type: 'melee',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'swing',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 22,
            max: 18,
            width: 50,
            shape: 'cone',
          ),
          effects: [],
        ),
        Attack(
          name: 'slam',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 20,
            max: 7,
            width: 4,
            shape: 'diamond',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
  ];

  List<Item> rangedWeapons = [
    Item(
      name: 'boomerang',
      description: '',
      itemSlot: 'one hand',
      type: 'ranged',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'throw',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 20,
            max: 19,
            width: 5,
            shape: 'ring offset',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'kunai',
      description: '',
      itemSlot: 'one hand',
      type: 'ranged',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'throw',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 30,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 5,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'poison dart',
      description: '',
      itemSlot: 'one hand',
      type: 'ranged',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'shot',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 15,
            max: 20,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'javelins',
      description: '',
      itemSlot: 'one hand',
      type: 'ranged',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'throw',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 15,
            max: 30,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 5,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'whip',
      description: '',
      itemSlot: 'one hand',
      type: 'ranged',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'whip',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 23,
            max: 10,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'short bow',
      description: '',
      itemSlot: 'two hands',
      type: 'ranged',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'shot',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 35,
            max: 48,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'composite bow',
      description: '',
      itemSlot: 'two hands',
      type: 'ranged',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'shot',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 23,
            max: 60,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'long bow',
      description: '',
      itemSlot: 'two hands',
      type: 'ranged',
      needsReload: false,
      isLoaded: false,
      effects: [],
      attacks: [
        Attack(
          name: 'shot',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 50,
            max: 60,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'hand cannon',
      description: '',
      itemSlot: 'one hand',
      type: 'ranged',
      needsReload: true,
      isLoaded: true,
      effects: [],
      attacks: [
        Attack(
          name: 'shot',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 15,
            max: 30,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'hand crossbow',
      description: '',
      itemSlot: 'one hand',
      type: 'ranged',
      needsReload: true,
      isLoaded: true,
      effects: [],
      attacks: [
        Attack(
          name: 'shot',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 15,
            max: 30,
            width: 3.5,
            shape: 'circle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'light crossbow',
      description: '',
      itemSlot: 'two hands',
      type: 'ranged',
      needsReload: true,
      isLoaded: true,
      effects: [],
      attacks: [
        Attack(
          name: 'shot',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 15,
            max: 80,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'heavy crossbow',
      description: '',
      itemSlot: 'two hands',
      type: 'ranged',
      needsReload: true,
      isLoaded: true,
      effects: [],
      attacks: [
        Attack(
          name: 'shot',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 15,
            max: 100,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
    Item(
      name: 'musket',
      description: '',
      itemSlot: 'two hands',
      type: 'ranged',
      needsReload: true,
      isLoaded: true,
      effects: [],
      attacks: [
        Attack(
          name: 'shot',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 15,
            max: 80,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
        Attack(
          name: 'thrust',
          damage: Damage(pDamage: 0, mDamage: 0, rawDamage: 0),
          range: Range(
            min: 7,
            max: 25,
            width: 7,
            shape: 'triangle',
          ),
          effects: [],
        ),
      ],
      armor: Armor(pArmor: 0, mArmor: 0),
      numberOfUses: 100,
      weight: 0,
      value: 0,
    ),
  ];

  List<Item> armor = [
    // Item(
    //   name: 'boots',
    //   description: '',
    //   itemSlot: 'feet',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 1, mArmor: 0),
    //   weight: 1,
    //   value: 100,
    // ),
    // Item(
    //   name: 'gloves',
    //   description: '',
    //   itemSlot: 'hands',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 1, mArmor: 0),
    //   weight: 1,
    //   value: 100,
    // ),
    // Item(
    //   name: 'buckler',
    //   description: '',
    //   itemSlot: 'one hand',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 1, mArmor: 0),
    //   weight: 0,
    //   value: 200,
    // ),
    // Item(
    //   name: 'magic sandals',
    //   description: '',
    //   itemSlot: 'feet',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 0, mArmor: 1),
    //   weight: 1,
    //   value: 100,
    // ),
    // Item(
    //   name: 'helmet',
    //   description: '',
    //   itemSlot: 'head',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 2, mArmor: 0),
    //   weight: 1,
    //   value: 300,
    // ),
    // Item(
    //   name: 'light shield',
    //   description: '',
    //   itemSlot: 'one hand',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 2, mArmor: 0),
    //   weight: 1,
    //   value: 300,
    // ),
    // Item(
    //   name: 'magic robe',
    //   description: '',
    //   itemSlot: 'body',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 0, mArmor: 2),
    //   weight: 1,
    //   value: 300,
    // ),
    // Item(
    //   name: 'light armor',
    //   description: '',
    //   itemSlot: 'body',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 4, mArmor: 0),
    //   weight: 4,
    //   value: 400,
    // ),
    // Item(
    //   name: 'heavy shield',
    //   description: '',
    //   itemSlot: 'one hand',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 4, mArmor: 0),
    //   weight: 3,
    //   value: 500,
    // ),
    // Item(
    //   name: 'full helmet',
    //   description: '',
    //   itemSlot: 'head',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 4, mArmor: 0),
    //   weight: 2,
    //   value: 600,
    // ),
    // Item(
    //   name: 'magic shield',
    //   description: '',
    //   itemSlot: 'one hand',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 0, mArmor: 3),
    //   weight: 2,
    //   value: 400,
    // ),
    // Item(
    //   name: 'heavy armor',
    //   description: '',
    //   itemSlot: 'body',
    //   type: 'armor',
    //   needsReload: false,
    //   isLoaded: false,
    //   effects: [],
    //   attacks: [],
    //   armor: Armor(pArmor: 7, mArmor: 0),
    //   weight: 7,
    //   value: 700,
    // ),
  ];

  List<Item> ancient = [
    // Item(
    //   icon: AppImages.ancientSword,
    //   name: 'ancient sword',
    //   description: '',
    //   itemSlot: 'one hand',
    //   type: 'melee',
    //   pDamage: 3,
    //   pArmor: 0,
    //   mDamage: 2,
    //   mArmor: 0,
    //   weight: 2,
    //   value: 1600,
    //   maxRange: 15,
    //   minRange: 0,
    // ),
    // Item(
    //   icon: AppImages.ancientWarAxe,
    //   name: 'ancient war axe',
    //   description: '',
    //   itemSlot: 'two hands',
    //   type: 'melee',
    //   pDamage: 6,
    //   pArmor: 0,
    //   mDamage: 2,
    //   mArmor: 0,
    //   weight: 4,
    //   value: 1700,
    //   maxRange: 20,
    //   minRange: 25,
    // ),
    // Item(
    //   icon: AppImages.ancientBow,
    //   name: 'ancient bow',
    //   description: '',
    //   itemSlot: 'two hands',
    //   type: 'ranged',
    //   pDamage: 4,
    //   pArmor: 0,
    //   mDamage: 2,
    //   mArmor: 0,
    //   weight: 1,
    //   value: 1600,
    //   maxRange: 250,
    //   minRange: 90,
    // ),
    // Item(
    //   icon: AppImages.ancientSpellBook,
    //   name: 'ancient spellbook',
    //   description: '',
    //   itemSlot: 'one hand',
    //   type: 'ranged',
    //   pDamage: 0,
    //   pArmor: 0,
    //   mDamage: 6,
    //   mArmor: 0,
    //   weight: 2,
    //   value: 1900,
    //   maxRange: 40,
    //   minRange: 0,
    // ),
    // Item(
    //   icon: AppImages.ancientGloves,
    //   name: 'ancient gloves',
    //   description: '',
    //   itemSlot: 'hands',
    //   type: 'armor',
    //   pDamage: 0,
    //   pArmor: 1,
    //   mDamage: 0,
    //   mArmor: 1,
    //   weight: 0,
    //   value: 800,
    //   maxRange: 0,
    //   minRange: 0,
    // ),
    // Item(
    //   icon: AppImages.ancientBoots,
    //   name: 'ancient boots',
    //   description: '',
    //   itemSlot: 'feet',
    //   type: 'armor',
    //   pDamage: 0,
    //   pArmor: 2,
    //   mDamage: 0,
    //   mArmor: 1,
    //   weight: 1,
    //   value: 900,
    //   maxRange: 0,
    //   minRange: 0,
    // ),
    // Item(
    //   icon: AppImages.ancientHelmet,
    //   name: 'ancient helmet',
    //   description: '',
    //   itemSlot: 'head',
    //   type: 'armor',
    //   pDamage: 0,
    //   pArmor: 4,
    //   mDamage: 0,
    //   mArmor: 2,
    //   weight: 2,
    //   value: 1200,
    //   maxRange: 0,
    //   minRange: 0,
    // ),
    // Item(
    //   icon: AppImages.ancientShield,
    //   name: 'ancient shield',
    //   description: '',
    //   itemSlot: 'one hand',
    //   type: 'armor',
    //   pDamage: 0,
    //   pArmor: 3,
    //   mDamage: 0,
    //   mArmor: 2,
    //   weight: 2,
    //   value: 1600,
    //   maxRange: 0,
    //   minRange: 0,
    // ),
    // Item(
    //   icon: AppImages.ancientArmor,
    //   name: 'ancient armor',
    //   description: '',
    //   itemSlot: 'body',
    //   type: 'armor',
    //   pDamage: 0,
    //   pArmor: 5,
    //   mDamage: 0,
    //   mArmor: 2,
    //   weight: 3,
    //   value: 1600,
    //   maxRange: 0,
    //   minRange: 0,
    // ),
  ];

  List<Item> consumable = [
    // Item(
    //   icon: AppImages.ward,
    //   name: 'ward',
    //   description: 'Reveals an area around you',
    //   itemSlot: 'consumable',
    //   type: 'consumable',
    //   weight: 1,
    //   value: 100,
    //   pDamage: 0,
    //   pArmor: 0,
    //   mDamage: 0,
    //   mArmor: 0,
    //   maxRange: 0,
    //   minRange: 0,
    // ),
    // Item(
    //   icon: AppImages.food,
    //   name: 'food',
    //   description: 'Heals 1-3 HP',
    //   itemSlot: 'consumable',
    //   type: 'consumable',
    //   weight: 1,
    //   value: 100,
    //   pDamage: 0,
    //   pArmor: 0,
    //   mDamage: 0,
    //   mArmor: 0,
    //   maxRange: 0,
    //   minRange: 0,
    // ),
    // Item(
    //   icon: AppImages.healingPotion,
    //   name: 'healing potion',
    //   description: 'Heals 3-6 HP',
    //   itemSlot: 'consumable',
    //   type: 'consumable',
    //   weight: 1,
    //   value: 300,
    //   pDamage: 0,
    //   pArmor: 0,
    //   mDamage: 0,
    //   mArmor: 0,
    //   maxRange: 0,
    //   minRange: 0,
    // ),
  ];
}
